### ISSUE TITLE
[Feature Request] Windows support

### ISSUE THREAD

**Issue by crusaderky** [supercharge/mongodb-github-action#7]
It would be great to have Windows support.

I am currently using this script as a workaround: https://gist.github.com/kamsar/98681b73979adc89610c

The script is hardcoded to 3.2.7 and falls over when upgrading to 4.2, though. Not sure about how to enable replica sets either.

**Comment by marcuspoehls** [comment]
@crusaderky Hey, I currently don’t have the time to support a Windows version of this GitHub Action. This GH Action uses Docker and Docker Actions aren’t yet supported on Windows hosts. We would need to maintain a workaround. I wouldn’t use this workaround because I can rely on a Linux host. The best way to support this GH Action on Windows would be Docker support on Windows hosts in GitHub Actions 😄
